//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPICombinePositionInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICombinePositionInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICombinePositionInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICombinePositionInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPICombinePositionInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionStreamID {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_PositionStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_PositionStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineStrategy {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineStrategy_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineStrategy_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionQty {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_PositionQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_PositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide1 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_OrderSide1_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_OrderSide1_get(swigCPtr);
      return ret;
    } 
  }

  public uint CombineQty1 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineQty1_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineQty1_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag1 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_HedgeFlag1_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_HedgeFlag1_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide2 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_OrderSide2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_OrderSide2_get(swigCPtr);
      return ret;
    } 
  }

  public uint CombineQty2 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CombineQty2_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag2 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_HedgeFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_HedgeFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountInitialMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_AccountInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_AccountInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountMaintenanceMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_AccountMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_AccountMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperInitialMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_UpperInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_UpperInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMaintenanceMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_UpperMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICombinePositionInfo_UpperMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICombinePositionInfo() : this(TapTradeCppWrapperPINVOKE.new_TapAPICombinePositionInfo(), true) {
  }

}
