//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIFundData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIFundData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIFundData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIFundData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIFundData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double TradeRate {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_TradeRate_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_TradeRate_get(swigCPtr);
      return ret;
    } 
  }

  public char FutureAlg {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_FutureAlg_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_FutureAlg_get(swigCPtr);
      return ret;
    } 
  }

  public char OptionAlg {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_OptionAlg_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_OptionAlg_get(swigCPtr);
      return ret;
    } 
  }

  public double PreBalance {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PreBalance_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PreBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double PreUnExpProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PreUnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PreUnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PreLMEPositionProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PreLMEPositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PreLMEPositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PreEquity {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PreEquity_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PreEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double PreAvailable1 {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PreAvailable1_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PreAvailable1_get(swigCPtr);
      return ret;
    } 
  }

  public double PreMarketEquity {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PreMarketEquity_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PreMarketEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double CashInValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CashInValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CashInValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CashOutValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CashOutValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CashOutValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CashAdjustValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CashAdjustValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CashAdjustValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CashPledged {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CashPledged_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CashPledged_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenFee {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_FrozenFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_FrozenFee_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenDeposit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_FrozenDeposit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_FrozenDeposit_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFee {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountFee_get(swigCPtr);
      return ret;
    } 
  }

  public double SwapInValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_SwapInValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_SwapInValue_get(swigCPtr);
      return ret;
    } 
  }

  public double SwapOutValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_SwapOutValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_SwapOutValue_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumIncome {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PremiumIncome_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PremiumIncome_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumPay {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PremiumPay_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PremiumPay_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenFund {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_FrozenFund_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_FrozenFund_get(swigCPtr);
      return ret;
    } 
  }

  public double UnExpProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_UnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_UnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double ExpProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_ExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_ExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double LmePositionProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_LmePositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_LmePositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionMarketValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_OptionMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_OptionMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountIntialMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountIntialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountIntialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountMaintenanceMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_AccountMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperInitalMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_UpperInitalMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_UpperInitalMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMaintenanceMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_UpperMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_UpperMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double Discount {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_Discount_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_Discount_get(swigCPtr);
      return ret;
    } 
  }

  public double Balance {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_Balance_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_Balance_get(swigCPtr);
      return ret;
    } 
  }

  public double Equity {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_Equity_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_Equity_get(swigCPtr);
      return ret;
    } 
  }

  public double Available {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_Available_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_Available_get(swigCPtr);
      return ret;
    } 
  }

  public double CanDraw {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_CanDraw_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_CanDraw_get(swigCPtr);
      return ret;
    } 
  }

  public double MarketEquity {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_MarketEquity_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_MarketEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double AuthMoney {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFundData_AuthMoney_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFundData_AuthMoney_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIFundData() : this(TapTradeCppWrapperPINVOKE.new_TapAPIFundData(), true) {
  }

}
