//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIRequestVertificateCodeRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIRequestVertificateCodeRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIRequestVertificateCodeRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIRequestVertificateCodeRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIRequestVertificateCodeRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string SecondSerialID {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIRequestVertificateCodeRsp_SecondSerialID_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIRequestVertificateCodeRsp_SecondSerialID_get(swigCPtr);
      return ret;
    } 
  }

  public int Effective {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIRequestVertificateCodeRsp_Effective_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradeCppWrapperPINVOKE.TapAPIRequestVertificateCodeRsp_Effective_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIRequestVertificateCodeRsp() : this(TapTradeCppWrapperPINVOKE.new_TapAPIRequestVertificateCodeRsp(), true) {
  }

}
