//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPICloseInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICloseInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICloseInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICloseInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPICloseInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseSide {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseSide_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseQty {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseQty_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenPrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_OpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_OpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_ClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_ClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_OpenMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_OpenMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchDateTime {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_OpenMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_OpenMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchDateTime {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseStreamId {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPICloseInfo_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICloseInfo() : this(TapTradeCppWrapperPINVOKE.new_TapAPICloseInfo(), true) {
  }

}
