//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ITapTradeAPI : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ITapTradeAPI(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ITapTradeAPI obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ITapTradeAPI() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_ITapTradeAPI(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual int SetAPINotify(ITapTradeAPINotify pSpi) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_SetAPINotify(swigCPtr, ITapTradeAPINotify.getCPtr(pSpi));
    return ret;
  }

  public virtual int SetHostAddress(string IP, ushort port, bool bSSL) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_SetHostAddress__SWIG_0(swigCPtr, IP, port, bSSL);
    return ret;
  }

  public virtual int SetHostAddress(string IP, ushort port) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_SetHostAddress__SWIG_1(swigCPtr, IP, port);
    return ret;
  }

  public virtual int Login(TapAPITradeLoginAuth loginAuth) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_Login(swigCPtr, TapAPITradeLoginAuth.getCPtr(loginAuth));
    return ret;
  }

  public virtual int RequestVertificateCode(out uint sessionID, string ContactInfo) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_RequestVertificateCode(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), ContactInfo);
    return ret;
  }

  public virtual int SetVertificateCode(out uint sessionID, TapAPISecondCertificationReq req) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_SetVertificateCode(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISecondCertificationReq.getCPtr(req));
    return ret;
  }

  public virtual int Disconnect() {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_Disconnect(swigCPtr);
    return ret;
  }

  public virtual int ChangePassword(out uint sessionID, TapAPIChangePasswordReq req) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_ChangePassword(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIChangePasswordReq.getCPtr(req));
    return ret;
  }

  public virtual int AuthPassword(out uint sessionID, TapAPIAuthPasswordReq req) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_AuthPassword(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAuthPasswordReq.getCPtr(req));
    return ret;
  }

  public virtual int HaveCertainRight(int rightID) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_HaveCertainRight(swigCPtr, rightID);
    return ret;
  }

  public virtual int QryTradingDate(out uint sessionID) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryTradingDate(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int SetReservedInfo(out uint sessionID, string info) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_SetReservedInfo(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), info);
    return ret;
  }

  public virtual int QryAccount(out uint sessionID, TapAPIAccQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryAccount(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryFund(out uint sessionID, TapAPIFundReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryFund(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFundReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryExchange(out uint sessionID) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryExchange(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int QryCommodity(out uint sessionID) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryCommodity(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int QryContract(out uint sessionID, TapAPICommodity qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryContract(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPICommodity.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertOrder(out uint sessionID, out string ClientOrderNo, TapAPINewOrder order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_InsertOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), SWIGTYPE_p_a_51__char.getCPtr(ClientOrderNo), TapAPINewOrder.getCPtr(order));
    return ret;
  }

  public virtual int CancelOrder(out uint sessionID, TapAPIOrderCancelReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_CancelOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderCancelReq.getCPtr(order));
    return ret;
  }

  public virtual int AmendOrder(out uint sessionID, TapAPIAmendOrder order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_AmendOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAmendOrder.getCPtr(order));
    return ret;
  }

  public virtual int ActivateOrder(out uint sessionID, TapAPIOrderCancelReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_ActivateOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderCancelReq.getCPtr(order));
    return ret;
  }

  public virtual int QryOrder(out uint sessionID, TapAPIOrderQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryOrderProcess(out uint sessionID, TapAPIOrderProcessQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryOrderProcess(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderProcessQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryFill(out uint sessionID, TapAPIFillQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryFill(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFillQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryPosition(out uint sessionID, TapAPIPositionQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryPosition(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIPositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryPositionSummary(out uint sessionID, TapAPIPositionQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryPositionSummary(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIPositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryCurrency(out uint sessionID) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryCurrency(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int QryAccountCashAdjust(out uint sessionID, TapAPIAccountCashAdjustQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryAccountCashAdjust(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountCashAdjustQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryTradeMessage(out uint sessionID, TapAPITradeMessageReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryTradeMessage(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPITradeMessageReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryBill(out uint sessionID, TapAPIBillQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryBill(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIBillQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisOrder(out uint sessionID, TapAPIHisOrderQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryHisOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisOrderProcess(out uint sessionID, TapAPIHisOrderProcessQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryHisOrderProcess(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisOrderProcessQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisMatch(out uint sessionID, TapAPIHisMatchQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryHisMatch(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisMatchQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisPosition(out uint sessionID, TapAPIHisPositionQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryHisPosition(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisPositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisDelivery(out uint sessionID, TapAPIHisDeliveryQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryHisDelivery(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisDeliveryQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryAccountFeeRent(out uint sessionID, TapAPIAccountFeeRentQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryAccountFeeRent(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountFeeRentQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryAccountMarginRent(out uint sessionID, TapAPIAccountMarginRentQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryAccountMarginRent(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountMarginRentQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertHKMarketOrder(out uint sessionID, out string ClientBuyOrderNo, out string ClientSellOrderNo, TapAPIOrderMarketInsertReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_InsertHKMarketOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), SWIGTYPE_p_a_51__char.getCPtr(ClientBuyOrderNo), SWIGTYPE_p_a_51__char.getCPtr(ClientSellOrderNo), TapAPIOrderMarketInsertReq.getCPtr(order));
    return ret;
  }

  public virtual int CancelHKMarketOrder(out uint sessionID, TapAPIOrderMarketDeleteReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_CancelHKMarketOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderMarketDeleteReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalRemove(out uint sessionID, TapAPIOrderLocalRemoveReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_OrderLocalRemove(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalRemoveReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalInput(out uint sessionID, TapAPIOrderLocalInputReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_OrderLocalInput(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalInputReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalModify(out uint sessionID, TapAPIOrderLocalModifyReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_OrderLocalModify(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalModifyReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalTransfer(out uint sessionID, TapAPIOrderLocalTransferReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_OrderLocalTransfer(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalTransferReq.getCPtr(order));
    return ret;
  }

  public virtual int FillLocalInput(out uint sessionID, TapAPIFillLocalInputReq fill) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_FillLocalInput(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFillLocalInputReq.getCPtr(fill));
    return ret;
  }

  public virtual int FillLocalRemove(out uint sessionID, TapAPIFillLocalRemoveReq fill) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_FillLocalRemove(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFillLocalRemoveReq.getCPtr(fill));
    return ret;
  }

  public virtual int QrySpotLock(out uint sessionID, TapAPISpotLockQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QrySpotLock(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISpotLockQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int SubmitUserLoginInfo(out uint sessionID, TapAPISubmitUserLoginInfo qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_SubmitUserLoginInfo(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISubmitUserLoginInfo.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertSpecialOrder(out uint sessionID, out string clientorderno, TapAPISpecialOrderInsertReq order) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_InsertSpecialOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), SWIGTYPE_p_a_51__char.getCPtr(clientorderno), TapAPISpecialOrderInsertReq.getCPtr(order));
    return ret;
  }

  public virtual int QrySpecialOrder(out uint sessionID, TapAPISpecialOrderQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QrySpecialOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISpecialOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryCombinePosition(out uint sessionID, TapAPICombinePositionQryReq qryReq) {
    int ret = TapTradeCppWrapperPINVOKE.ITapTradeAPI_QryCombinePosition(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPICombinePositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public ITapTradeAPI() : this(TapTradeCppWrapperPINVOKE.new_ITapTradeAPI(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("SetAPINotify", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateITapTradeAPI_0(SwigDirectorMethodSetAPINotify);
    if (SwigDerivedClassHasMethod("SetHostAddress", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateITapTradeAPI_1(SwigDirectorMethodSetHostAddress__SWIG_0);
    if (SwigDerivedClassHasMethod("SetHostAddress", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateITapTradeAPI_2(SwigDirectorMethodSetHostAddress__SWIG_1);
    if (SwigDerivedClassHasMethod("Login", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateITapTradeAPI_3(SwigDirectorMethodLogin);
    if (SwigDerivedClassHasMethod("RequestVertificateCode", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateITapTradeAPI_4(SwigDirectorMethodRequestVertificateCode);
    if (SwigDerivedClassHasMethod("SetVertificateCode", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateITapTradeAPI_5(SwigDirectorMethodSetVertificateCode);
    if (SwigDerivedClassHasMethod("Disconnect", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateITapTradeAPI_6(SwigDirectorMethodDisconnect);
    if (SwigDerivedClassHasMethod("ChangePassword", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateITapTradeAPI_7(SwigDirectorMethodChangePassword);
    if (SwigDerivedClassHasMethod("AuthPassword", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateITapTradeAPI_8(SwigDirectorMethodAuthPassword);
    if (SwigDerivedClassHasMethod("HaveCertainRight", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateITapTradeAPI_9(SwigDirectorMethodHaveCertainRight);
    if (SwigDerivedClassHasMethod("QryTradingDate", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateITapTradeAPI_10(SwigDirectorMethodQryTradingDate);
    if (SwigDerivedClassHasMethod("SetReservedInfo", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateITapTradeAPI_11(SwigDirectorMethodSetReservedInfo);
    if (SwigDerivedClassHasMethod("QryAccount", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateITapTradeAPI_12(SwigDirectorMethodQryAccount);
    if (SwigDerivedClassHasMethod("QryFund", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateITapTradeAPI_13(SwigDirectorMethodQryFund);
    if (SwigDerivedClassHasMethod("QryExchange", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateITapTradeAPI_14(SwigDirectorMethodQryExchange);
    if (SwigDerivedClassHasMethod("QryCommodity", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateITapTradeAPI_15(SwigDirectorMethodQryCommodity);
    if (SwigDerivedClassHasMethod("QryContract", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateITapTradeAPI_16(SwigDirectorMethodQryContract);
    if (SwigDerivedClassHasMethod("InsertOrder", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateITapTradeAPI_17(SwigDirectorMethodInsertOrder);
    if (SwigDerivedClassHasMethod("CancelOrder", swigMethodTypes18))
      swigDelegate18 = new SwigDelegateITapTradeAPI_18(SwigDirectorMethodCancelOrder);
    if (SwigDerivedClassHasMethod("AmendOrder", swigMethodTypes19))
      swigDelegate19 = new SwigDelegateITapTradeAPI_19(SwigDirectorMethodAmendOrder);
    if (SwigDerivedClassHasMethod("ActivateOrder", swigMethodTypes20))
      swigDelegate20 = new SwigDelegateITapTradeAPI_20(SwigDirectorMethodActivateOrder);
    if (SwigDerivedClassHasMethod("QryOrder", swigMethodTypes21))
      swigDelegate21 = new SwigDelegateITapTradeAPI_21(SwigDirectorMethodQryOrder);
    if (SwigDerivedClassHasMethod("QryOrderProcess", swigMethodTypes22))
      swigDelegate22 = new SwigDelegateITapTradeAPI_22(SwigDirectorMethodQryOrderProcess);
    if (SwigDerivedClassHasMethod("QryFill", swigMethodTypes23))
      swigDelegate23 = new SwigDelegateITapTradeAPI_23(SwigDirectorMethodQryFill);
    if (SwigDerivedClassHasMethod("QryPosition", swigMethodTypes24))
      swigDelegate24 = new SwigDelegateITapTradeAPI_24(SwigDirectorMethodQryPosition);
    if (SwigDerivedClassHasMethod("QryPositionSummary", swigMethodTypes25))
      swigDelegate25 = new SwigDelegateITapTradeAPI_25(SwigDirectorMethodQryPositionSummary);
    if (SwigDerivedClassHasMethod("QryCurrency", swigMethodTypes26))
      swigDelegate26 = new SwigDelegateITapTradeAPI_26(SwigDirectorMethodQryCurrency);
    if (SwigDerivedClassHasMethod("QryAccountCashAdjust", swigMethodTypes27))
      swigDelegate27 = new SwigDelegateITapTradeAPI_27(SwigDirectorMethodQryAccountCashAdjust);
    if (SwigDerivedClassHasMethod("QryTradeMessage", swigMethodTypes28))
      swigDelegate28 = new SwigDelegateITapTradeAPI_28(SwigDirectorMethodQryTradeMessage);
    if (SwigDerivedClassHasMethod("QryBill", swigMethodTypes29))
      swigDelegate29 = new SwigDelegateITapTradeAPI_29(SwigDirectorMethodQryBill);
    if (SwigDerivedClassHasMethod("QryHisOrder", swigMethodTypes30))
      swigDelegate30 = new SwigDelegateITapTradeAPI_30(SwigDirectorMethodQryHisOrder);
    if (SwigDerivedClassHasMethod("QryHisOrderProcess", swigMethodTypes31))
      swigDelegate31 = new SwigDelegateITapTradeAPI_31(SwigDirectorMethodQryHisOrderProcess);
    if (SwigDerivedClassHasMethod("QryHisMatch", swigMethodTypes32))
      swigDelegate32 = new SwigDelegateITapTradeAPI_32(SwigDirectorMethodQryHisMatch);
    if (SwigDerivedClassHasMethod("QryHisPosition", swigMethodTypes33))
      swigDelegate33 = new SwigDelegateITapTradeAPI_33(SwigDirectorMethodQryHisPosition);
    if (SwigDerivedClassHasMethod("QryHisDelivery", swigMethodTypes34))
      swigDelegate34 = new SwigDelegateITapTradeAPI_34(SwigDirectorMethodQryHisDelivery);
    if (SwigDerivedClassHasMethod("QryAccountFeeRent", swigMethodTypes35))
      swigDelegate35 = new SwigDelegateITapTradeAPI_35(SwigDirectorMethodQryAccountFeeRent);
    if (SwigDerivedClassHasMethod("QryAccountMarginRent", swigMethodTypes36))
      swigDelegate36 = new SwigDelegateITapTradeAPI_36(SwigDirectorMethodQryAccountMarginRent);
    if (SwigDerivedClassHasMethod("InsertHKMarketOrder", swigMethodTypes37))
      swigDelegate37 = new SwigDelegateITapTradeAPI_37(SwigDirectorMethodInsertHKMarketOrder);
    if (SwigDerivedClassHasMethod("CancelHKMarketOrder", swigMethodTypes38))
      swigDelegate38 = new SwigDelegateITapTradeAPI_38(SwigDirectorMethodCancelHKMarketOrder);
    if (SwigDerivedClassHasMethod("OrderLocalRemove", swigMethodTypes39))
      swigDelegate39 = new SwigDelegateITapTradeAPI_39(SwigDirectorMethodOrderLocalRemove);
    if (SwigDerivedClassHasMethod("OrderLocalInput", swigMethodTypes40))
      swigDelegate40 = new SwigDelegateITapTradeAPI_40(SwigDirectorMethodOrderLocalInput);
    if (SwigDerivedClassHasMethod("OrderLocalModify", swigMethodTypes41))
      swigDelegate41 = new SwigDelegateITapTradeAPI_41(SwigDirectorMethodOrderLocalModify);
    if (SwigDerivedClassHasMethod("OrderLocalTransfer", swigMethodTypes42))
      swigDelegate42 = new SwigDelegateITapTradeAPI_42(SwigDirectorMethodOrderLocalTransfer);
    if (SwigDerivedClassHasMethod("FillLocalInput", swigMethodTypes43))
      swigDelegate43 = new SwigDelegateITapTradeAPI_43(SwigDirectorMethodFillLocalInput);
    if (SwigDerivedClassHasMethod("FillLocalRemove", swigMethodTypes44))
      swigDelegate44 = new SwigDelegateITapTradeAPI_44(SwigDirectorMethodFillLocalRemove);
    if (SwigDerivedClassHasMethod("QrySpotLock", swigMethodTypes45))
      swigDelegate45 = new SwigDelegateITapTradeAPI_45(SwigDirectorMethodQrySpotLock);
    if (SwigDerivedClassHasMethod("SubmitUserLoginInfo", swigMethodTypes46))
      swigDelegate46 = new SwigDelegateITapTradeAPI_46(SwigDirectorMethodSubmitUserLoginInfo);
    if (SwigDerivedClassHasMethod("InsertSpecialOrder", swigMethodTypes47))
      swigDelegate47 = new SwigDelegateITapTradeAPI_47(SwigDirectorMethodInsertSpecialOrder);
    if (SwigDerivedClassHasMethod("QrySpecialOrder", swigMethodTypes48))
      swigDelegate48 = new SwigDelegateITapTradeAPI_48(SwigDirectorMethodQrySpecialOrder);
    if (SwigDerivedClassHasMethod("QryCombinePosition", swigMethodTypes49))
      swigDelegate49 = new SwigDelegateITapTradeAPI_49(SwigDirectorMethodQryCombinePosition);
    TapTradeCppWrapperPINVOKE.ITapTradeAPI_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17, swigDelegate18, swigDelegate19, swigDelegate20, swigDelegate21, swigDelegate22, swigDelegate23, swigDelegate24, swigDelegate25, swigDelegate26, swigDelegate27, swigDelegate28, swigDelegate29, swigDelegate30, swigDelegate31, swigDelegate32, swigDelegate33, swigDelegate34, swigDelegate35, swigDelegate36, swigDelegate37, swigDelegate38, swigDelegate39, swigDelegate40, swigDelegate41, swigDelegate42, swigDelegate43, swigDelegate44, swigDelegate45, swigDelegate46, swigDelegate47, swigDelegate48, swigDelegate49);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ITapTradeAPI));
    return hasDerivedMethod;
  }

  private int SwigDirectorMethodSetAPINotify(global::System.IntPtr pSpi) {
    return SetAPINotify((pSpi == global::System.IntPtr.Zero) ? null : new ITapTradeAPINotify(pSpi, false));
  }

  private int SwigDirectorMethodSetHostAddress__SWIG_0(string IP, ushort port, bool bSSL) {
    return SetHostAddress(IP, port, bSSL);
  }

  private int SwigDirectorMethodSetHostAddress__SWIG_1(string IP, ushort port) {
    return SetHostAddress(IP, port);
  }

  private int SwigDirectorMethodLogin(global::System.IntPtr loginAuth) {
    return Login((loginAuth == global::System.IntPtr.Zero) ? null : new TapAPITradeLoginAuth(loginAuth, false));
  }

  private int SwigDirectorMethodRequestVertificateCode(out uint sessionID, string ContactInfo) {
    return RequestVertificateCode((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), ContactInfo);
  }

  private int SwigDirectorMethodSetVertificateCode(out uint sessionID, global::System.IntPtr req) {
    return SetVertificateCode((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (req == global::System.IntPtr.Zero) ? null : new TapAPISecondCertificationReq(req, false));
  }

  private int SwigDirectorMethodDisconnect() {
    return Disconnect();
  }

  private int SwigDirectorMethodChangePassword(out uint sessionID, global::System.IntPtr req) {
    return ChangePassword((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (req == global::System.IntPtr.Zero) ? null : new TapAPIChangePasswordReq(req, false));
  }

  private int SwigDirectorMethodAuthPassword(out uint sessionID, global::System.IntPtr req) {
    return AuthPassword((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (req == global::System.IntPtr.Zero) ? null : new TapAPIAuthPasswordReq(req, false));
  }

  private int SwigDirectorMethodHaveCertainRight(int rightID) {
    return HaveCertainRight(rightID);
  }

  private int SwigDirectorMethodQryTradingDate(out uint sessionID) {
    return QryTradingDate((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodSetReservedInfo(out uint sessionID, string info) {
    return SetReservedInfo((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), info);
  }

  private int SwigDirectorMethodQryAccount(out uint sessionID, global::System.IntPtr qryReq) {
    return QryAccount((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryFund(out uint sessionID, global::System.IntPtr qryReq) {
    return QryFund((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIFundReq(qryReq, false));
  }

  private int SwigDirectorMethodQryExchange(out uint sessionID) {
    return QryExchange((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodQryCommodity(out uint sessionID) {
    return QryCommodity((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodQryContract(out uint sessionID, global::System.IntPtr qryReq) {
    return QryContract((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPICommodity(qryReq, false));
  }

  private int SwigDirectorMethodInsertOrder(out uint sessionID, out string ClientOrderNo, global::System.IntPtr order) {
    return InsertOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (ClientOrderNo == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(ClientOrderNo, false), (order == global::System.IntPtr.Zero) ? null : new TapAPINewOrder(order, false));
  }

  private int SwigDirectorMethodCancelOrder(out uint sessionID, global::System.IntPtr order) {
    return CancelOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderCancelReq(order, false));
  }

  private int SwigDirectorMethodAmendOrder(out uint sessionID, global::System.IntPtr order) {
    return AmendOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIAmendOrder(order, false));
  }

  private int SwigDirectorMethodActivateOrder(out uint sessionID, global::System.IntPtr order) {
    return ActivateOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderCancelReq(order, false));
  }

  private int SwigDirectorMethodQryOrder(out uint sessionID, global::System.IntPtr qryReq) {
    return QryOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIOrderQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryOrderProcess(out uint sessionID, global::System.IntPtr qryReq) {
    return QryOrderProcess((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIOrderProcessQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryFill(out uint sessionID, global::System.IntPtr qryReq) {
    return QryFill((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIFillQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryPosition(out uint sessionID, global::System.IntPtr qryReq) {
    return QryPosition((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIPositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryPositionSummary(out uint sessionID, global::System.IntPtr qryReq) {
    return QryPositionSummary((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIPositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryCurrency(out uint sessionID) {
    return QryCurrency((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodQryAccountCashAdjust(out uint sessionID, global::System.IntPtr qryReq) {
    return QryAccountCashAdjust((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountCashAdjustQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryTradeMessage(out uint sessionID, global::System.IntPtr qryReq) {
    return QryTradeMessage((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPITradeMessageReq(qryReq, false));
  }

  private int SwigDirectorMethodQryBill(out uint sessionID, global::System.IntPtr qryReq) {
    return QryBill((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIBillQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisOrder(out uint sessionID, global::System.IntPtr qryReq) {
    return QryHisOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisOrderQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisOrderProcess(out uint sessionID, global::System.IntPtr qryReq) {
    return QryHisOrderProcess((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisOrderProcessQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisMatch(out uint sessionID, global::System.IntPtr qryReq) {
    return QryHisMatch((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisMatchQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisPosition(out uint sessionID, global::System.IntPtr qryReq) {
    return QryHisPosition((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisPositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisDelivery(out uint sessionID, global::System.IntPtr qryReq) {
    return QryHisDelivery((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisDeliveryQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryAccountFeeRent(out uint sessionID, global::System.IntPtr qryReq) {
    return QryAccountFeeRent((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountFeeRentQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryAccountMarginRent(out uint sessionID, global::System.IntPtr qryReq) {
    return QryAccountMarginRent((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountMarginRentQryReq(qryReq, false));
  }

  private int SwigDirectorMethodInsertHKMarketOrder(out uint sessionID, out string ClientBuyOrderNo, out string ClientSellOrderNo, global::System.IntPtr order) {
    return InsertHKMarketOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (ClientBuyOrderNo == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(ClientBuyOrderNo, false), (ClientSellOrderNo == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(ClientSellOrderNo, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderMarketInsertReq(order, false));
  }

  private int SwigDirectorMethodCancelHKMarketOrder(out uint sessionID, global::System.IntPtr order) {
    return CancelHKMarketOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderMarketDeleteReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalRemove(out uint sessionID, global::System.IntPtr order) {
    return OrderLocalRemove((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalRemoveReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalInput(out uint sessionID, global::System.IntPtr order) {
    return OrderLocalInput((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalInputReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalModify(out uint sessionID, global::System.IntPtr order) {
    return OrderLocalModify((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalModifyReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalTransfer(out uint sessionID, global::System.IntPtr order) {
    return OrderLocalTransfer((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalTransferReq(order, false));
  }

  private int SwigDirectorMethodFillLocalInput(out uint sessionID, global::System.IntPtr fill) {
    return FillLocalInput((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (fill == global::System.IntPtr.Zero) ? null : new TapAPIFillLocalInputReq(fill, false));
  }

  private int SwigDirectorMethodFillLocalRemove(out uint sessionID, global::System.IntPtr fill) {
    return FillLocalRemove((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (fill == global::System.IntPtr.Zero) ? null : new TapAPIFillLocalRemoveReq(fill, false));
  }

  private int SwigDirectorMethodQrySpotLock(out uint sessionID, global::System.IntPtr qryReq) {
    return QrySpotLock((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPISpotLockQryReq(qryReq, false));
  }

  private int SwigDirectorMethodSubmitUserLoginInfo(out uint sessionID, global::System.IntPtr qryReq) {
    return SubmitUserLoginInfo((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPISubmitUserLoginInfo(qryReq, false));
  }

  private int SwigDirectorMethodInsertSpecialOrder(out uint sessionID, out string clientorderno, global::System.IntPtr order) {
    return InsertSpecialOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (clientorderno == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(clientorderno, false), (order == global::System.IntPtr.Zero) ? null : new TapAPISpecialOrderInsertReq(order, false));
  }

  private int SwigDirectorMethodQrySpecialOrder(out uint sessionID, global::System.IntPtr qryReq) {
    return QrySpecialOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPISpecialOrderQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryCombinePosition(out uint sessionID, global::System.IntPtr qryReq) {
    return QryCombinePosition((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPICombinePositionQryReq(qryReq, false));
  }

  public delegate int SwigDelegateITapTradeAPI_0(global::System.IntPtr pSpi);
  public delegate int SwigDelegateITapTradeAPI_1(string IP, ushort port, bool bSSL);
  public delegate int SwigDelegateITapTradeAPI_2(string IP, ushort port);
  public delegate int SwigDelegateITapTradeAPI_3(global::System.IntPtr loginAuth);
  public delegate int SwigDelegateITapTradeAPI_4(out uint sessionID, string ContactInfo);
  public delegate int SwigDelegateITapTradeAPI_5(out uint sessionID, global::System.IntPtr req);
  public delegate int SwigDelegateITapTradeAPI_6();
  public delegate int SwigDelegateITapTradeAPI_7(out uint sessionID, global::System.IntPtr req);
  public delegate int SwigDelegateITapTradeAPI_8(out uint sessionID, global::System.IntPtr req);
  public delegate int SwigDelegateITapTradeAPI_9(int rightID);
  public delegate int SwigDelegateITapTradeAPI_10(out uint sessionID);
  public delegate int SwigDelegateITapTradeAPI_11(out uint sessionID, string info);
  public delegate int SwigDelegateITapTradeAPI_12(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_13(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_14(out uint sessionID);
  public delegate int SwigDelegateITapTradeAPI_15(out uint sessionID);
  public delegate int SwigDelegateITapTradeAPI_16(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_17(out uint sessionID, out string ClientOrderNo, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_18(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_19(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_20(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_21(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_22(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_23(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_24(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_25(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_26(out uint sessionID);
  public delegate int SwigDelegateITapTradeAPI_27(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_28(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_29(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_30(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_31(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_32(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_33(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_34(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_35(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_36(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_37(out uint sessionID, out string ClientBuyOrderNo, out string ClientSellOrderNo, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_38(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_39(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_40(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_41(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_42(out uint sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_43(out uint sessionID, global::System.IntPtr fill);
  public delegate int SwigDelegateITapTradeAPI_44(out uint sessionID, global::System.IntPtr fill);
  public delegate int SwigDelegateITapTradeAPI_45(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_46(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_47(out uint sessionID, out string clientorderno, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_48(out uint sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_49(out uint sessionID, global::System.IntPtr qryReq);

  private SwigDelegateITapTradeAPI_0 swigDelegate0;
  private SwigDelegateITapTradeAPI_1 swigDelegate1;
  private SwigDelegateITapTradeAPI_2 swigDelegate2;
  private SwigDelegateITapTradeAPI_3 swigDelegate3;
  private SwigDelegateITapTradeAPI_4 swigDelegate4;
  private SwigDelegateITapTradeAPI_5 swigDelegate5;
  private SwigDelegateITapTradeAPI_6 swigDelegate6;
  private SwigDelegateITapTradeAPI_7 swigDelegate7;
  private SwigDelegateITapTradeAPI_8 swigDelegate8;
  private SwigDelegateITapTradeAPI_9 swigDelegate9;
  private SwigDelegateITapTradeAPI_10 swigDelegate10;
  private SwigDelegateITapTradeAPI_11 swigDelegate11;
  private SwigDelegateITapTradeAPI_12 swigDelegate12;
  private SwigDelegateITapTradeAPI_13 swigDelegate13;
  private SwigDelegateITapTradeAPI_14 swigDelegate14;
  private SwigDelegateITapTradeAPI_15 swigDelegate15;
  private SwigDelegateITapTradeAPI_16 swigDelegate16;
  private SwigDelegateITapTradeAPI_17 swigDelegate17;
  private SwigDelegateITapTradeAPI_18 swigDelegate18;
  private SwigDelegateITapTradeAPI_19 swigDelegate19;
  private SwigDelegateITapTradeAPI_20 swigDelegate20;
  private SwigDelegateITapTradeAPI_21 swigDelegate21;
  private SwigDelegateITapTradeAPI_22 swigDelegate22;
  private SwigDelegateITapTradeAPI_23 swigDelegate23;
  private SwigDelegateITapTradeAPI_24 swigDelegate24;
  private SwigDelegateITapTradeAPI_25 swigDelegate25;
  private SwigDelegateITapTradeAPI_26 swigDelegate26;
  private SwigDelegateITapTradeAPI_27 swigDelegate27;
  private SwigDelegateITapTradeAPI_28 swigDelegate28;
  private SwigDelegateITapTradeAPI_29 swigDelegate29;
  private SwigDelegateITapTradeAPI_30 swigDelegate30;
  private SwigDelegateITapTradeAPI_31 swigDelegate31;
  private SwigDelegateITapTradeAPI_32 swigDelegate32;
  private SwigDelegateITapTradeAPI_33 swigDelegate33;
  private SwigDelegateITapTradeAPI_34 swigDelegate34;
  private SwigDelegateITapTradeAPI_35 swigDelegate35;
  private SwigDelegateITapTradeAPI_36 swigDelegate36;
  private SwigDelegateITapTradeAPI_37 swigDelegate37;
  private SwigDelegateITapTradeAPI_38 swigDelegate38;
  private SwigDelegateITapTradeAPI_39 swigDelegate39;
  private SwigDelegateITapTradeAPI_40 swigDelegate40;
  private SwigDelegateITapTradeAPI_41 swigDelegate41;
  private SwigDelegateITapTradeAPI_42 swigDelegate42;
  private SwigDelegateITapTradeAPI_43 swigDelegate43;
  private SwigDelegateITapTradeAPI_44 swigDelegate44;
  private SwigDelegateITapTradeAPI_45 swigDelegate45;
  private SwigDelegateITapTradeAPI_46 swigDelegate46;
  private SwigDelegateITapTradeAPI_47 swigDelegate47;
  private SwigDelegateITapTradeAPI_48 swigDelegate48;
  private SwigDelegateITapTradeAPI_49 swigDelegate49;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(ITapTradeAPINotify) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(string), typeof(ushort), typeof(bool) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(string), typeof(ushort) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(TapAPITradeLoginAuth) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(string) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPISecondCertificationReq) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes7 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIChangePasswordReq) };
  private static global::System.Type[] swigMethodTypes8 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIAuthPasswordReq) };
  private static global::System.Type[] swigMethodTypes9 = new global::System.Type[] { typeof(int) };
  private static global::System.Type[] swigMethodTypes10 = new global::System.Type[] { typeof(uint).MakeByRefType() };
  private static global::System.Type[] swigMethodTypes11 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(string) };
  private static global::System.Type[] swigMethodTypes12 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIAccQryReq) };
  private static global::System.Type[] swigMethodTypes13 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIFundReq) };
  private static global::System.Type[] swigMethodTypes14 = new global::System.Type[] { typeof(uint).MakeByRefType() };
  private static global::System.Type[] swigMethodTypes15 = new global::System.Type[] { typeof(uint).MakeByRefType() };
  private static global::System.Type[] swigMethodTypes16 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPICommodity) };
  private static global::System.Type[] swigMethodTypes17 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(string).MakeByRefType(), typeof(TapAPINewOrder) };
  private static global::System.Type[] swigMethodTypes18 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderCancelReq) };
  private static global::System.Type[] swigMethodTypes19 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIAmendOrder) };
  private static global::System.Type[] swigMethodTypes20 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderCancelReq) };
  private static global::System.Type[] swigMethodTypes21 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderQryReq) };
  private static global::System.Type[] swigMethodTypes22 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderProcessQryReq) };
  private static global::System.Type[] swigMethodTypes23 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIFillQryReq) };
  private static global::System.Type[] swigMethodTypes24 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIPositionQryReq) };
  private static global::System.Type[] swigMethodTypes25 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIPositionQryReq) };
  private static global::System.Type[] swigMethodTypes26 = new global::System.Type[] { typeof(uint).MakeByRefType() };
  private static global::System.Type[] swigMethodTypes27 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIAccountCashAdjustQryReq) };
  private static global::System.Type[] swigMethodTypes28 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPITradeMessageReq) };
  private static global::System.Type[] swigMethodTypes29 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIBillQryReq) };
  private static global::System.Type[] swigMethodTypes30 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIHisOrderQryReq) };
  private static global::System.Type[] swigMethodTypes31 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIHisOrderProcessQryReq) };
  private static global::System.Type[] swigMethodTypes32 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIHisMatchQryReq) };
  private static global::System.Type[] swigMethodTypes33 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIHisPositionQryReq) };
  private static global::System.Type[] swigMethodTypes34 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIHisDeliveryQryReq) };
  private static global::System.Type[] swigMethodTypes35 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIAccountFeeRentQryReq) };
  private static global::System.Type[] swigMethodTypes36 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIAccountMarginRentQryReq) };
  private static global::System.Type[] swigMethodTypes37 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(string).MakeByRefType(), typeof(string).MakeByRefType(), typeof(TapAPIOrderMarketInsertReq) };
  private static global::System.Type[] swigMethodTypes38 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderMarketDeleteReq) };
  private static global::System.Type[] swigMethodTypes39 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderLocalRemoveReq) };
  private static global::System.Type[] swigMethodTypes40 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderLocalInputReq) };
  private static global::System.Type[] swigMethodTypes41 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderLocalModifyReq) };
  private static global::System.Type[] swigMethodTypes42 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIOrderLocalTransferReq) };
  private static global::System.Type[] swigMethodTypes43 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIFillLocalInputReq) };
  private static global::System.Type[] swigMethodTypes44 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIFillLocalRemoveReq) };
  private static global::System.Type[] swigMethodTypes45 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPISpotLockQryReq) };
  private static global::System.Type[] swigMethodTypes46 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPISubmitUserLoginInfo) };
  private static global::System.Type[] swigMethodTypes47 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(string).MakeByRefType(), typeof(TapAPISpecialOrderInsertReq) };
  private static global::System.Type[] swigMethodTypes48 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPISpecialOrderQryReq) };
  private static global::System.Type[] swigMethodTypes49 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPICombinePositionQryReq) };
}
