//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIOrderMarketInsertRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderMarketInsertRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIOrderMarketInsertRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIOrderMarketInsertRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIOrderMarketInsertRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char BuyPositionEffect {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_BuyPositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_BuyPositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char SellPositionEffect {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_SellPositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_SellPositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderBuyPrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderSellPrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderBuyQty {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderSellQty {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellQty_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderBuyNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSellNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellNo_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderMarketUserNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderMarketTime {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketTime_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public double RefDouble {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefDouble_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefDouble_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientBuyOrderNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientBuyOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientBuyOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientSellOrderNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientSellOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientSellOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorText {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorText_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorText_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientLocalIP {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientLocalIP_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientLocalIP_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientMac {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientMac_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientMac_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientIP {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientIP_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientIP_get(swigCPtr);
      return ret;
    } 
  }

  public string Remark {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_Remark_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIOrderMarketInsertRsp_Remark_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderMarketInsertRsp() : this(TapTradeCppWrapperPINVOKE.new_TapAPIOrderMarketInsertRsp(), true) {
  }

}
