//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIAccountFeeRentQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountFeeRentQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountFeeRentQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIAccountFeeRentQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIAccountFeeRentQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char CalculateMode {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CalculateMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CalculateMode_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenCloseFee {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_OpenCloseFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_OpenCloseFee_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseTodayFee {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CloseTodayFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountFeeRentQryRsp_CloseTodayFee_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountFeeRentQryRsp() : this(TapTradeCppWrapperPINVOKE.new_TapAPIAccountFeeRentQryRsp(), true) {
  }

}
