//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIAccountMarginRentQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountMarginRentQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountMarginRentQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIAccountMarginRentQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIAccountMarginRentQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char CalculateMode {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CalculateMode_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CalculateMode_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double InitialMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_InitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_InitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double MaintenanceMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_MaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_MaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellInitialMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_SellInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_SellInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellMaintenanceMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_SellMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_SellMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LockMargin {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_LockMargin_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIAccountMarginRentQryRsp_LockMargin_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountMarginRentQryRsp() : this(TapTradeCppWrapperPINVOKE.new_TapAPIAccountMarginRentQryRsp(), true) {
  }

}
