//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TapAPIFillLocalInputReq : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIFillLocalInputReq(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIFillLocalInputReq obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIFillLocalInputReq() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeCppWrapperPINVOKE.delete_TapAPIFillLocalInputReq(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSide {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double MatchPrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchQty {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSystemNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_OrderSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_OrderSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_UpperMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_UpperMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchDateTime {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_MatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchDateTime {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_UpperMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_UpperMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_FeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_FeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_FeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_FeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeValue {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_FeeValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_FeeValue_get(swigCPtr);
      return ret;
    } 
  }

  public char IsManualFee {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_IsManualFee_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_IsManualFee_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePositionPrice {
    set {
      TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_ClosePositionPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeCppWrapperPINVOKE.TapAPIFillLocalInputReq_ClosePositionPrice_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIFillLocalInputReq() : this(TapTradeCppWrapperPINVOKE.new_TapAPIFillLocalInputReq(), true) {
  }

}
